language: node_js
node_js:
  - "7.5.0"
  - "7"
script:
  - npm run test:unit
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# - provider: script
#     script: deploy.sh production
#     on:
#       branch: master
